//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: comppsc
// Function body: comppscFunctionMap.cxx

#include    "comppscFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createcomppscFunctionMap()
{


	XSModelFunction::addFunctionPointer( "compPSc",    new XSCall<xsf77Call>(xscomppscf_) );

}
