//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: comppsc Created :
// Initializer: comppsc.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "comppscFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Comppsc_Init(Tcl_Interp* tclInterp);
extern "C" int Comppsc_SafeInit(Tcl_Interp* tclInterp);

int Comppsc_Init(Tcl_Interp* tclInterp)
{
        return Comppsc_SafeInit(tclInterp);
}

int Comppsc_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "comppsc";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/epiphyllum/Library/CloudStorage/OneDrive-Personal/Subjects/Constant_compton_y_in_the_AGN_corona/compps_conv/lmodel_comppsc.dat");
        createcomppscFunctionMap();
        return TCL_OK;

}

